#import <UIKit/UIKit.h>
#import <MapKit/MapKit.h>
#import <CoreLocation/CoreLocation.h>

static NSString *const FGEnabled=@"FGEnabled",*const FGHidden=@"FGHidden",*const FGX=@"FGX",*const FGY=@"FGY";
static NSUserDefaults *D(void){return NSUserDefaults.standardUserDefaults;}
static UIColor *C(CGFloat r,CGFloat g,CGFloat b){return [UIColor colorWithRed:r/255.0 green:g/255.0 blue:b/255.0 alpha:1];}
static UIImage *S(NSString*n){if(@available(iOS 13.0,*))return [UIImage systemImageNamed:n];return nil;}

@interface FGController:UIViewController<MKMapViewDelegate,UISearchBarDelegate,UIImagePickerControllerDelegate,UINavigationControllerDelegate>
@property UIButton *floating; @property UIView *panel; @property MKMapView *map; @property UILabel *coord; @property UIImageView *preview; @property NSInteger volumeCount; @property NSTimeInterval lastVolume;
@end
@implementation FGController
-(void)viewDidLoad{[super viewDidLoad];self.view.backgroundColor=UIColor.clearColor;[self buildFloating];[[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(volumeChanged:) name:@"AVSystemController_SystemVolumeDidChangeNotification" object:nil];}
-(void)buildFloating{self.floating=[UIButton buttonWithType:UIButtonTypeSystem];self.floating.frame=CGRectMake(20,150,64,64);self.floating.layer.cornerRadius=32;self.floating.tintColor=UIColor.whiteColor;[self.floating setImage:S(@"location.fill") forState:0];[self.floating addTarget:self action:@selector(openPanel) forControlEvents:UIControlEventTouchUpInside];[self.floating addGestureRecognizer:[[UIPanGestureRecognizer alloc]initWithTarget:self action:@selector(drag:)]];double x=[D()doubleForKey:FGX],y=[D()doubleForKey:FGY];if(x>0&&y>0)self.floating.center=CGPointMake(x,y);self.floating.hidden=[D()boolForKey:FGHidden];[self refreshColor];[self.view addSubview:self.floating];}
-(void)refreshColor{BOOL on=[D()boolForKey:FGEnabled];self.floating.backgroundColor=on?C(70,226,123):C(104,113,125);self.floating.layer.shadowColor=(on?C(70,226,123):UIColor.blackColor).CGColor;self.floating.layer.shadowOpacity=.45;self.floating.layer.shadowRadius=14;}
-(void)drag:(UIPanGestureRecognizer*)g{CGPoint t=[g translationInView:self.view];self.floating.center=CGPointMake(self.floating.center.x+t.x,self.floating.center.y+t.y);[g setTranslation:CGPointZero inView:self.view];if(g.state==UIGestureRecognizerStateEnded){[D()setDouble:self.floating.center.x forKey:FGX];[D()setDouble:self.floating.center.y forKey:FGY];}}
-(void)volumeChanged:(NSNotification*)n{float v=[n.userInfo[@"AVSystemController_AudioVolumeNotificationParameter"]floatValue];static float old=-1;if(old>=0&&v>old){NSTimeInterval now=NSDate.date.timeIntervalSince1970;if(now-self.lastVolume>1.5)self.volumeCount=0;self.lastVolume=now;if(++self.volumeCount>=3){self.volumeCount=0;self.floating.hidden=NO;[D()setBool:NO forKey:FGHidden];}}old=v;}
-(UIButton*)btn:(NSString*)title symbol:(NSString*)sym color:(UIColor*)color{UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.backgroundColor=color;b.layer.cornerRadius=14;b.tintColor=UIColor.whiteColor;[b setTitle:title forState:0];[b setTitleColor:UIColor.whiteColor forState:0];[b setImage:S(sym) forState:0];b.titleLabel.font=[UIFont boldSystemFontOfSize:14];return b;}
-(void)openPanel{self.panel=[[UIView alloc]initWithFrame:self.view.bounds];self.panel.backgroundColor=C(5,7,11);[self.view addSubview:self.panel];UILabel*t=[[UILabel alloc]initWithFrame:CGRectMake(70,45,self.view.bounds.size.width-140,44)];t.text=@"FAKE GPS";t.textColor=UIColor.whiteColor;t.font=[UIFont boldSystemFontOfSize:24];t.textAlignment=1;[self.panel addSubview:t];UIButton*close=[self btn:@"إغلاق" symbol:@"xmark" color:C(44,54,68)];close.frame=CGRectMake(16,48,74,40);[close addTarget:self action:@selector(closePanel) forControlEvents:64];[self.panel addSubview:close];UISearchBar*s=[[UISearchBar alloc]initWithFrame:CGRectMake(14,96,self.view.bounds.size.width-28,50)];s.placeholder=@"مدينة، عنوان، أو إحداثيات";s.delegate=self;s.searchBarStyle=UISearchBarStyleMinimal;[self.panel addSubview:s];self.map=[[MKMapView alloc]initWithFrame:CGRectMake(14,152,self.view.bounds.size.width-28,self.view.bounds.size.height-340)];self.map.layer.cornerRadius=22;self.map.delegate=self;self.map.showsUserLocation=YES;[self.panel addSubview:self.map];self.coord=[[UILabel alloc]initWithFrame:CGRectMake(14,self.view.bounds.size.height-178,self.view.bounds.size.width-28,42)];self.coord.text=@"24.713600, 46.675300";self.coord.textColor=UIColor.whiteColor;self.coord.textAlignment=1;self.coord.backgroundColor=C(17,26,36);self.coord.layer.cornerRadius=13;self.coord.clipsToBounds=YES;[self.panel addSubview:self.coord];UIButton*toggle=[self btn:@"تفعيل الموقع" symbol:@"location.fill" color:C(71,140,255)];toggle.frame=CGRectMake(14,self.view.bounds.size.height-126,(self.view.bounds.size.width-42)/2,50);[toggle addTarget:self action:@selector(toggleGPS) forControlEvents:64];[self.panel addSubview:toggle];UIButton*photos=[self btn:@"الصور" symbol:@"photo.on.rectangle" color:C(154,140,255)];photos.frame=CGRectMake(28+(self.view.bounds.size.width-42)/2,self.view.bounds.size.height-126,(self.view.bounds.size.width-42)/2,50);[photos addTarget:self action:@selector(openPhotos) forControlEvents:64];[self.panel addSubview:photos];}
-(void)closePanel{[self.panel removeFromSuperview];self.panel=nil;}
-(void)toggleGPS{BOOL on=![D()boolForKey:FGEnabled];[D()setBool:on forKey:FGEnabled];[self refreshColor];}
-(void)openPhotos{UIImagePickerController*p=[UIImagePickerController new];p.sourceType=UIImagePickerControllerSourceTypePhotoLibrary;p.delegate=self;[self presentViewController:p animated:YES completion:nil];}
-(void)imagePickerController:(UIImagePickerController*)p didFinishPickingMediaWithInfo:(NSDictionary*)info{UIImage*i=info[UIImagePickerControllerOriginalImage];if(i)[self.floating setImage:i forState:0];[p dismissViewControllerAnimated:YES completion:nil];}
-(void)searchBarSearchButtonClicked:(UISearchBar*)s{[s resignFirstResponder];MKLocalSearchRequest*r=[MKLocalSearchRequest new];r.naturalLanguageQuery=s.text;MKLocalSearch*x=[[MKLocalSearch alloc]initWithRequest:r];[x startWithCompletionHandler:^(MKLocalSearchResponse*res,NSError*e){if(res.mapItems.count){CLLocationCoordinate2D c=res.mapItems.firstObject.placemark.coordinate;dispatch_async(dispatch_get_main_queue(),^{[self.map setRegion:MKCoordinateRegionMakeWithDistance(c,900,900) animated:YES];self.coord.text=[NSString stringWithFormat:@"%.6f, %.6f",c.latitude,c.longitude];});}}];}
@end
static UIWindow*w;__attribute__((constructor))static void initFG(){dispatch_async(dispatch_get_main_queue(),^{w=[[UIWindow alloc]initWithFrame:UIScreen.mainScreen.bounds];w.windowLevel=UIWindowLevelAlert+50;w.backgroundColor=UIColor.clearColor;w.rootViewController=[FGController new];w.hidden=NO;});}
