<?php
declare(strict_types=1);
$configFile = dirname(__DIR__) . '/config.php';
if (!is_file($configFile)) { header('Location: ../install.php'); exit; }
$config = require $configFile;
session_name((string)($config['admin_session_name'] ?? 'gpsq_admin'));
session_start();
function db(): PDO { global $config; static $pdo; if($pdo instanceof PDO)return $pdo; $pdo=new PDO('sqlite:'.$config['database_path']);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$pdo->exec('PRAGMA foreign_keys=ON');return $pdo; }
function h(string $v): string { return htmlspecialchars($v,ENT_QUOTES,'UTF-8'); }
function csrf(): string { if(empty($_SESSION['gpsq_csrf']))$_SESSION['gpsq_csrf']=bin2hex(random_bytes(24));return (string)$_SESSION['gpsq_csrf']; }
function checkcsrf(): void { if(!hash_equals(csrf(),(string)($_POST['csrf']??'')))throw new RuntimeException('جلسة غير صالحة'); }
function now(): string { return date(DATE_ATOM); }
$error='';$message='';
if(isset($_GET['logout'])){$_SESSION=[];session_destroy();header('Location: index.php');exit;}
if(empty($_SESSION['gpsq_admin_id'])){
 if($_SERVER['REQUEST_METHOD']==='POST'){try{$s=db()->prepare('SELECT * FROM admins WHERE username=? LIMIT 1');$s->execute([trim((string)($_POST['username']??''))]);$u=$s->fetch();if(!$u||!password_verify((string)($_POST['password']??''),(string)$u['password_hash']))throw new RuntimeException('بيانات الدخول غير صحيحة');$_SESSION['gpsq_admin_id']=$u['id'];$_SESSION['gpsq_admin_user']=$u['username'];header('Location: index.php');exit;}catch(Throwable $e){$error=$e->getMessage();}}
 ?><!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>دخول GPSQ</title><link rel="stylesheet" href="style.css"><body class="login"><form class="card login-card" method="post"><h1>GPSQ</h1><p>لوحة إدارة التفعيل</p><?php if($error):?><div class="alert error"><?=h($error)?></div><?php endif;?><input name="username" placeholder="اسم المستخدم" required><input type="password" name="password" placeholder="كلمة المرور" required><button>دخول</button></form></body></html><?php exit;
}
$pdo=db();$page=(string)($_GET['page']??'dashboard');
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{checkcsrf();$action=(string)($_POST['action']??'');
  if($action==='create'){$count=max(1,min(200,(int)($_POST['count']??1)));$days=max(1,(int)($_POST['days']??30));$limit=max(1,min(10,(int)($_POST['limit']??1)));$name=trim((string)($_POST['name']??''));$stmt=$pdo->prepare('INSERT INTO licenses(code,customer_name,is_active,device_limit,expires_at,created_at) VALUES(?,?,1,?,?,?)');$alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for($i=0;$i<$count;$i++){$suffix='';for($j=0;$j<4;$j++)$suffix.=$alphabet[random_int(0,strlen($alphabet)-1)];$stmt->execute(['GPSQ'.$suffix,$name,$limit,date(DATE_ATOM,strtotime('+'.$days.' days')),now()]);}$message='تم إنشاء الأكواد';$page='codes';}
  elseif($action==='toggle'){$pdo->prepare('UPDATE licenses SET is_active=CASE WHEN is_active=1 THEN 0 ELSE 1 END,updated_at=? WHERE id=?')->execute([now(),(int)$_POST['id']]);$page='codes';}
  elseif($action==='reset'){$id=(int)$_POST['id'];$pdo->prepare('DELETE FROM activation_sessions WHERE license_id=?')->execute([$id]);$pdo->prepare('DELETE FROM license_devices WHERE license_id=?')->execute([$id]);$page='codes';}
  elseif($action==='delete'){$pdo->prepare('DELETE FROM licenses WHERE id=?')->execute([(int)$_POST['id']]);$page='codes';}
  elseif($action==='disconnect'){$id=(int)$_POST['id'];$q=$pdo->prepare('SELECT license_id,device_hash FROM license_devices WHERE id=?');$q->execute([$id]);$d=$q->fetch();if($d){$pdo->prepare('DELETE FROM activation_sessions WHERE license_id=? AND device_hash=?')->execute([$d['license_id'],$d['device_hash']]);$pdo->prepare('DELETE FROM license_devices WHERE id=?')->execute([$id]);}$page='devices';}
 }catch(Throwable $e){$message=$e->getMessage();}
}
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GPSQ Admin</title><link rel="stylesheet" href="style.css"></head><body><aside><h2>GPSQ</h2><a href="?page=dashboard">الرئيسية</a><a href="?page=codes">الأكواد</a><a href="?page=devices">الأجهزة</a><a href="?page=logs">السجل</a><a href="../api/status.php" target="_blank">API</a><a href="?logout=1">خروج</a></aside><main><header><h1><?=h(['dashboard'=>'لوحة المعلومات','codes'=>'الأكواد','devices'=>'الأجهزة','logs'=>'السجل'][$page]??'GPSQ')?></h1><span><?=h((string)($_SESSION['gpsq_admin_user']??''))?></span></header><?php if($message):?><div class="card message"><?=h($message)?></div><?php endif;?>
<?php if($page==='dashboard'):$stats=['الأكواد'=>(int)$pdo->query('SELECT COUNT(*) FROM licenses')->fetchColumn(),'الفعالة'=>(int)$pdo->query('SELECT COUNT(*) FROM licenses WHERE is_active=1')->fetchColumn(),'الأجهزة'=>(int)$pdo->query('SELECT COUNT(*) FROM license_devices')->fetchColumn(),'الجلسات'=>(int)$pdo->query("SELECT COUNT(*) FROM activation_sessions WHERE expires_at > datetime('now')")->fetchColumn()];?><section class="grid"><?php foreach($stats as $k=>$v):?><article class="card"><b><?=h($k)?></b><strong><?=$v?></strong></article><?php endforeach;?></section><section class="card"><h2>مسارات الربط</h2><code>POST /activation/api/activate.php</code><code>POST /activation/api/verify.php</code><code>POST /activation/api/deactivate.php</code></section>
<?php elseif($page==='codes'):$rows=$pdo->query('SELECT l.*,(SELECT COUNT(*) FROM license_devices d WHERE d.license_id=l.id) device_count FROM licenses l ORDER BY l.id DESC LIMIT 500')->fetchAll();?><div class="card"><form method="post" class="form-row"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="create"><input type="number" name="count" min="1" max="200" value="1"><input type="number" name="days" min="1" value="30"><input type="number" name="limit" min="1" max="10" value="1"><input name="name" placeholder="اسم العميل"><button>إنشاء</button></form></div><div class="table-wrap"><table><tr><th>الكود</th><th>العميل</th><th>الحالة</th><th>الأجهزة</th><th>الانتهاء</th><th>إجراء</th></tr><?php foreach($rows as $r):?><tr><td><code><?=h($r['code'])?></code></td><td><?=h((string)$r['customer_name'])?></td><td><?=$r['is_active']?'فعال':'موقوف'?></td><td><?=$r['device_count']?> / <?=$r['device_limit']?></td><td><?=h((string)$r['expires_at'])?></td><td><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button name="action" value="toggle">تبديل</button><button name="action" value="reset">فصل</button><button class="danger" name="action" value="delete" onclick="return confirm('حذف؟')">حذف</button></form></td></tr><?php endforeach;?></table></div>
<?php elseif($page==='devices'):$rows=$pdo->query('SELECT d.*,l.code,l.customer_name FROM license_devices d JOIN licenses l ON l.id=d.license_id ORDER BY d.last_seen_at DESC')->fetchAll();?><div class="table-wrap"><table><tr><th>الكود</th><th>العميل</th><th>معرف الجهاز</th><th>أول تفعيل</th><th>آخر اتصال</th><th></th></tr><?php foreach($rows as $r):?><tr><td><code><?=h($r['code'])?></code></td><td><?=h((string)$r['customer_name'])?></td><td><code><?=h(substr($r['device_hash'],0,18))?>…</code></td><td><?=h($r['created_at'])?></td><td><?=h($r['last_seen_at'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger" name="action" value="disconnect">فصل</button></form></td></tr><?php endforeach;?></table></div>
<?php elseif($page==='logs'):$rows=$pdo->query('SELECT a.*,l.code FROM activation_logs a LEFT JOIN licenses l ON l.id=a.license_id ORDER BY a.id DESC LIMIT 500')->fetchAll();?><div class="table-wrap"><table><tr><th>الوقت</th><th>الحدث</th><th>الكود</th><th>IP</th><th>التفاصيل</th></tr><?php foreach($rows as $r):?><tr><td><?=h($r['created_at'])?></td><td><?=h($r['event'])?></td><td><?=h((string)$r['code'])?></td><td><?=h((string)$r['ip_address'])?></td><td><code><?=h((string)$r['details'])?></code></td></tr><?php endforeach;?></table></div><?php endif;?></main></body></html>
